### ISSUE TITLE
perl TE_Orthology.pl

### ISSUE THREAD

**Issue by zuodabin** [4ureliek/TEorthology#1]
there are some problem that I am encounted 
like this:
perl TE_Orthology.pl -cpus 20 -dir /nfs_fs/nfs4/sunyb/zuobin/TE/TE_oth -blast /nfs_fs/nfs4/sunyb/miniconda3/bin
find: ‘/nfs_fs/nfs4/sunyb/zuobin/TE/orthology.TE_oth/DATA/*.extract/’: No such file or directory

**Comment by 4ureliek** [comment]
Can you run these 2 commands and send me what you get?
`ls -al /nfs_fs/nfs4/sunyb/zuobin/TE/orthology.TE_oth/`
`ls -al /nfs_fs/nfs4/sunyb/zuobin/TE/orthology.TE_oth/DATA/`

**Comment by zuodabin** [comment]
hi~，result like this :
ls -al /nfs_fs/nfs4/sunyb/zuobin/TE/TE_oth/result/
total 8
drwxr-xr-x 4 sunyb sunyb&nbsp; &nbsp;89 Aug 30 22:02 .
drwxrwxr-x 3 sunyb sunyb 4096 Aug 30 22:02 ..
drwxr-xr-x 2 sunyb sunyb&nbsp; &nbsp;10 Aug 30 21:58 DATA
drwxr-xr-x 2 sunyb sunyb&nbsp; &nbsp;10 Aug 30 21:58 DATA_Fa_no-seq
-rw-rw-r-- 1 sunyb sunyb&nbsp; 472 Aug 30 22:02 _TE_Orthology.results.tab





ls -al /nfs_fs/nfs4/sunyb/zuobin/frog-genome/TE/TE_oth/result/DATA/


total 0
drwxr-xr-x 2 sunyb sunyb 10 Aug 30 21:58 .
drwxr-xr-x 4 sunyb sunyb 89 Aug 30 22:02 ..



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "4ureliek/TEorthology"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月7日(星期三) 凌晨2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [4ureliek/TEorthology] perl TE_Orthology.pl (Issue #1)





 
Can you run these 2 commands and send me what you get?
 ls -al /nfs_fs/nfs4/sunyb/zuobin/TE/orthology.TE_oth/
 ls -al /nfs_fs/nfs4/sunyb/zuobin/TE/orthology.TE_oth/DATA/

**Comment by 4ureliek** [comment]
Could I get your full log? Feel free to email it to me directly. The folders weren't created in DATA and my bet is something went wrong upstream of the error you shared.

**Comment by zuodabin** [comment]
Hi，the logs has email to you&nbsp;in the appendix&nbsp;&nbsp;,thinks!!!
and some folder has maked&nbsp; ,but its all empty!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "4ureliek/TEorthology"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 凌晨2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [4ureliek/TEorthology] perl TE_Orthology.pl (Issue #1)





 
Could I get your full log? Feel free to email it to me directly. The folders weren't created in DATA and my bet is something went wrong upstream of the error you shared.

**Comment by 4ureliek** [comment]
I didn't get the email - please send to 4urelie.k at gmail.com
